config/routes.rb
Rails.application.routes.draw do

  root 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true

  mount_uploader :photo, PhotoUploader

end
# through doses

app/models/dose.rb
class Dose < ActiveRecord::Base
belongs_to :cocktail
  belongs_to :ingredient

  validates :description , presence: true
  validates :cocktail, presence: true
  validates :ingredient , presence: true
  validates_uniqueness_of :ingredient_id, :scope => :cocktail_id
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :doses
  has_many :cocktails, through: :doses
  before_destroy :check_for_cocktails

  validates :name, presence: true, uniqueness: true

  private

  def check_for_cocktails
    if cocktails.count > 0
      errors.add_to_base("cannot delete ingredients while cocktails exist")
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :set_cocktail, only: [:show, :edit, :destroy]
  before_action :new_cocktail, only: [:index]

  def index
    @cocktails = Cocktail.all
  end
  def show
    @dose = Dose.new
  end

  def create

    @cocktail = Cocktail.create(cocktail_params)
    if @cocktail.save
      redirect_to root_path
    else
      render :new
    end
  end

  def new
    @cocktail = Cocktail.new
  end

  def destroy
    @cocktail.destroy
    redirect_to root_path
  end

  private
  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end

  def new_cocktail
    @cocktail = Cocktail.new
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [:update, :destroy]
  before_action :find_cocktails, only: [:new, :create]

  def create
    @dose = @cocktail.doses.create(dose_params)
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def new
    @dose = @cocktail.doses.build
  end

  def update
    @dose.update(dose_params)
  end

  def destroy
    @dose.destroy
    redirect_to @dose.cocktail
  end

  private
  def set_dose
    @dose = Dose.find(params[:id])
  end

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id )
  end

  def find_cocktails
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
  <div class="cocktail_form">
    <%= simple_form_for(@cocktail) do |f| %>
    <%= f.error_notification %>
    <%= f.input :name, label: false,required: false, placeholder: 'My new cocktail' %>
    <!-- photo uploader -->

    <%= f.input :photo, class: 'btn btn-primary btn-xs' %>
    <%= f.input :photo_cache, as: :hidden %>

    <%= f.button :submit, class: 'btn btn-yours' %>
    <% end %>
  </div>

app/views/cocktails/create.html.erb
<%= render 'form' %>

app/views/cocktails/edit.html.erb
<hr>
<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/cocktails/index.html.erb
 <div class="banner" style="background-image: linear-gradient(-225deg, rgba(128, 16, 136, 0.55) 0%, rgba(14, 0, 61, 0.6) 50%), url(<%= image_path 'cocktails.jpg'%>);">
  <div class="text-center banner-content">
    <h1>Mr Cocktail Program</h1>
    <p>All your favorite cocktails,<strong> in one place</strong></p>
    <a href="#" class="btn btn-yours">Drink</a>
  </div>
</div>


<div class="text-center padded">
  <h2>My Cocktails</h2>
  <div class="container padded">
    <div class="row">

      <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="cocktail">
          <%= link_to(cocktail_path(cocktail)) do %>
          <div> <%= cocktail.name %></div>
          <%= image_tag cocktail.photo.url(:thumb), class: 'img-rounded ' %>
          <% end %>
          <br>
          <div class="card-icon">
            <div class="card-add">
              <%= link_to '', new_cocktail_dose_path(cocktail), class: "fa fa-plus-circle" %>
            </div>
            <div class="card-trash">
          <%= link_to '', cocktail, method: :delete, class: 'fa fa-trash' %>
            </div>
          </div>

        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div class="jumbotron">
  <div class="row">
    <div class="text-center">
      <div class="col-xs-12 col-sm-offset-4 col-sm-4"><h2 class="text-center">Create</h2>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

<!--
css translate css transitions -->

app/views/cocktails/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
 <div class="banner" id="cocktail-show" style="background-image: linear-gradient(-225deg, rgba(128, 16, 136, 0.55) 0%, rgba(14, 0, 61, 0.6) 50%), url(<%= image_path 'cocktails.jpg'%>);">
  <div class="text-center banner-content">
    <h1><%= @cocktail.name %></h1>
    <p><strong> Tips and Ingredients..</strong></p>
  </div>
</div>

<div class="padded">
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 ">
    <!-- go back -->
<div>
    <%= link_to root_path do %>
    <i class="fa fa-arrow-left" aria-hidden="true"></i>
    <% end %>
</div>
    <!-- Cocktail image -->
      <%= image_tag @cocktail.photo.url(:standard) %>
    </div>
    <div class="col-xs-12 col-md-6 ">
      <div class="column">
        <div class="row">
          <div class="col-xs-4"><strong>Ingredients</strong></div>
          <div class="col-xs-4"><strong>Doses</strong></div>
          <div class="col-xs-4"><strong>Actions</strong></div>
        </div>
      </div>
      <br>
      <% @cocktail.ingredients.each do |ingredient| %>
      <div class="column">
        <div class="row">
          <div class="col-xs-4"><%= ingredient.name %></div>
          <div class="col-xs-4"> <% ingredient.doses.each do |dose| %>
            <%= dose.description %>
          </div>
          <div class="col-xs-4"><%= link_to 'Delete', dose, method: :delete, class: 'btn btn-delete' %></div>

        </div>
      </div>
      <% end %>
      <% end %>
<br>
<%= link_to 'Add dose', new_cocktail_dose_path(@cocktail), class: "btn btn-yours" %>
<br>
      <br>
    </div>
  </div>
</div>
<br>
</div>

app/views/doses/_form.html.erb
<div class="cocktail_form">
<%= simple_form_for [@cocktail, @dose] do |f| %>
<%= f.error_notification %>

<%= f.collection_select(:ingredient_id, Ingredient.all, :id, :name) %>

<%= f.input :description %>
<%= f.button :submit %>
<% end %>
</div>

app/views/doses/create.html 17-13-33-314.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/delete.html.erb
<h1>Doses#delete</h1>
<p>Find me in app/views/doses/delete.html.erb</p>

app/views/doses/new.html.erb
<p>Add and ingredient and its description for</p>
<h2>  <%= @cocktail.name %></h2>
<hr>
<%= render 'form' %>

app/views/doses/save.html.erb
<h1>Doses#save</h1>
<p>Find me in app/views/doses/save.html.erb</p>

app/views/doses/update.html.erb
<h1>Doses#update</h1>
<p>Find me in app/views/doses/update.html.erb</p>

app/views/layouts/_footer.html.erb
<div class="footer">
<div>
  <ul class="list-inline">
    <li><i class="fa fa-youtube fa-2x" aria-hidden="true"></i>
    </li>
    <li><i class="fa fa-instagram fa-2x" aria-hidden="true"></i>
    </li>
    <li><i class="fa fa-facebook fa-2x" aria-hidden="true"></i>
    </li>
    <li><i class="fa fa-twitter fa-2x" aria-hidden="true"></i>
    </li>
  </ul>
  </div>
  <div>
  <p>We love cocktails @ LeWagon</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>
<body>


     <%= yield %>


</body>
<%= render 'layouts/footer' %>
</html>